# Generated by Django 4.2.6 on 2024-03-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='produit',
        ),
    ]
